name: accidenyally
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.0
  clippy_flutter: ^1.0.0
  cupertino_icons: ^1.0.0
  carousel_slider: ^3.0.0
  flutter_staggered_grid_view: ^0.3.4
  google_fonts: ^1.1.2
  fluttertoast: ^7.1.8
  flip_card: ^0.4.4
  percent_indicator: "^2.1.1"
  flutter_switch: ^0.0.2
  firebase_auth: ^0.8.0
  cloud_firestore: ^0.10.0
  uuid: 2.2.2
  image_picker: ^0.6.3+4
  firebase_storage: ^2.1.0
  path_provider: ^1.3.0
  http: ^0.12.1
  image_viewer: ^1.0.0
  provider: ^4.3.3
  flutter_cached_pdfview: ^0.3.5
  loading_indicator: ^1.2.0
  form_field_validator: ^1.0.1
  auto_size_text: ^2.1.0
  geolocator: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
